// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement;

#nullable disable

namespace UserManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251214153132_LoadUserUpdate2")]
    partial class LoadUserUpdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Engines.Motorok", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Accelarations_On_The_Hill_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Accelarations_On_The_Hill_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Adhesion_factor")
                        .HasColumnType("REAL");

                    b.Property<double>("AirDensity")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("AirResistances_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AirResistances_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Ascent_resistance")
                        .HasColumnType("REAL");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Creep_factor")
                        .HasColumnType("REAL");

                    b.Property<double>("Cross_Section")
                        .HasColumnType("REAL");

                    b.Property<double>("Drag_coefficient")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Dynamic_Factors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ForceAgistTheCar_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ForceAgistTheCar_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Force_of_the_Wheels_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Force_of_the_Wheels_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ForcesRequiredForAccelaration_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ForcesRequiredForAccelaration_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gauge")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gear_ratio")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<double>("M_P_Max")
                        .HasColumnType("REAL");

                    b.Property<double>("M_max")
                        .HasColumnType("REAL");

                    b.Property<int>("Max_Weight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("P_M_Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Pn_max")
                        .HasColumnType("REAL");

                    b.Property<double>("Reduction_constant_of_rotating_masses")
                        .HasColumnType("REAL");

                    b.Property<double>("Rolling_resistance")
                        .HasColumnType("REAL");

                    b.Property<double>("Rolling_resistance_factor")
                        .HasColumnType("REAL");

                    b.Property<double>("Rolling_resistance_on_a_hill")
                        .HasColumnType("REAL");

                    b.Property<double>("Slope_of_rise")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Speed_In_Kmperh_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Speed_In_Kmperh_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Speed_of_the_Wheels_M")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Speed_of_the_Wheels_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("The_hill_on_degree")
                        .HasColumnType("REAL");

                    b.Property<string>("Tire")
                        .HasColumnType("TEXT");

                    b.Property<double>("Transmission_efficiency")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Transmissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<double>("Wheel_radius")
                        .HasColumnType("REAL");

                    b.Property<int>("Wheelbase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<double>("n_M_max")
                        .HasColumnType("REAL");

                    b.Property<double>("n_pn_max")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("Localization.LocalizationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalizationEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StrengthOfMaterials.MaterialStrength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseArea")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseSecondOrderMoment_X")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseSecondOrderMoment_XY")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseSecondOrderMoment_Y")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseWidth")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<double>("Force")
                        .HasColumnType("REAL");

                    b.Property<double>("I1")
                        .HasColumnType("REAL");

                    b.Property<double>("I2")
                        .HasColumnType("REAL");

                    b.Property<double>("Ix")
                        .HasColumnType("REAL");

                    b.Property<double>("Ixy")
                        .HasColumnType("REAL");

                    b.Property<double>("Iy")
                        .HasColumnType("REAL");

                    b.Property<double>("Maxstress")
                        .HasColumnType("REAL");

                    b.Property<double>("Minstress")
                        .HasColumnType("REAL");

                    b.Property<double>("NormalStress")
                        .HasColumnType("REAL");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("alfa")
                        .HasColumnType("REAL");

                    b.Property<double>("iOne")
                        .HasColumnType("REAL");

                    b.Property<double>("iTwo")
                        .HasColumnType("REAL");

                    b.Property<double>("ms")
                        .HasColumnType("REAL");

                    b.Property<double>("x0")
                        .HasColumnType("REAL");

                    b.Property<double>("x00")
                        .HasColumnType("REAL");

                    b.Property<double>("x10")
                        .HasColumnType("REAL");

                    b.Property<double>("x_0")
                        .HasColumnType("REAL");

                    b.Property<double>("xx10")
                        .HasColumnType("REAL");

                    b.Property<double>("xy10")
                        .HasColumnType("REAL");

                    b.Property<double>("y0")
                        .HasColumnType("REAL");

                    b.Property<double>("y00")
                        .HasColumnType("REAL");

                    b.Property<double>("y10")
                        .HasColumnType("REAL");

                    b.Property<double>("y_0")
                        .HasColumnType("REAL");

                    b.Property<double>("yx10")
                        .HasColumnType("REAL");

                    b.Property<double>("yy10")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MaterialStrength");
                });

            modelBuilder.Entity("StrengthOfMaterials.Point", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialStrengthId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("R")
                        .HasColumnType("REAL");

                    b.Property<int?>("SubRegionid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<int>("index")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("MaterialStrengthId");

                    b.HasIndex("SubRegionid");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("StrengthOfMaterials.SubRegion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AddedRegionOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Angle")
                        .HasColumnType("REAL");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<int?>("CutoutRegionOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("PlacementX")
                        .HasColumnType("REAL");

                    b.Property<double>("PlacementY")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("_radius")
                        .HasColumnType("REAL");

                    b.Property<double>("_subRegionCenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("_subRegionCenterY")
                        .HasColumnType("REAL");

                    b.Property<double>("secondOrderMoment_X")
                        .HasColumnType("REAL");

                    b.Property<double>("secondOrderMoment_XY")
                        .HasColumnType("REAL");

                    b.Property<double>("secondOrderMoment_Y")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("AddedRegionOwnerId");

                    b.HasIndex("CutoutRegionOwnerId");

                    b.ToTable("SubRegion");
                });

            modelBuilder.Entity("UserManagement.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialStrengthId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MaterialStrengthViewAccess")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Motorok")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MotorokViewAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UserManagement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UserManagement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UserManagement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrengthOfMaterials.Point", b =>
                {
                    b.HasOne("StrengthOfMaterials.MaterialStrength", "MaterialStrength")
                        .WithMany("MainPointList")
                        .HasForeignKey("MaterialStrengthId");

                    b.HasOne("StrengthOfMaterials.SubRegion", null)
                        .WithMany("Points")
                        .HasForeignKey("SubRegionid");

                    b.Navigation("MaterialStrength");
                });

            modelBuilder.Entity("StrengthOfMaterials.SubRegion", b =>
                {
                    b.HasOne("StrengthOfMaterials.MaterialStrength", "AddedRegionOwner")
                        .WithMany("AddedRegions")
                        .HasForeignKey("AddedRegionOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrengthOfMaterials.MaterialStrength", "CutoutRegionOwner")
                        .WithMany("CutoutRegions")
                        .HasForeignKey("CutoutRegionOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AddedRegionOwner");

                    b.Navigation("CutoutRegionOwner");
                });

            modelBuilder.Entity("StrengthOfMaterials.MaterialStrength", b =>
                {
                    b.Navigation("AddedRegions");

                    b.Navigation("CutoutRegions");

                    b.Navigation("MainPointList");
                });

            modelBuilder.Entity("StrengthOfMaterials.SubRegion", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
